name: Docker Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: https://index.docker.io/v1/

      - name: Build Docker image
        run: docker buildx build -t khaulaatiq/flaskTask --push

# yeh yml file docker hub pe image upload karegi humaray flask wali
